name: Docker Hub

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Dockerimages
        id: prepare
        run: |
          cd ubuntu
          chmod +x createDockerfiles.sh
          ./createDockerfiles.sh
          now=$(date '+%Y-%m')
          echo $now
          name='${{ vars.REPOIMAGE }}'
          armTag="${name}:arm-${now}"
          amdTag="${name}:amd-${now}"
          echo $armTag
          echo $amdTag

      - name: Build
        id: build
        run: |
          echo ${{ steps.prepare.outputs.image }}
          docker build -f Dockerfile-arm -t $armTag

